os: linux
dist: bionic

language: java

# disable clone depth because our tags are too far back in the history and the tests look for them
git:
  depth: false

install:
  - "./gradlew jar"

after_success:
  - ./gradlew jacocoTestReport coveralls
  - bash <(curl -s https://codecov.io/bash)


# gradle-specific cache configuration:
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"


notifications:
  slack:
    rooms:
      - secure: I4OIELFscbYzyPzIBhGftvVmlWB48F/swqumcQxjoIKJlbl8YSS9x1fXVdbT7qXBojJ/MQeZ6Tf0+IfcRN+2zUmOjmvIajp8FtdWYzEr2Ff5otSq/SaqURVtaQaHA6DoIPI7GnLOqJ3cl7282KoJUkHLUEf21VuXxIogo+Honvjl24UpBp7XHLzdv5LaLQneyC4zSC5Lhxea2FQrutA025QoepJAWlz4j9NSJYqJ/1aHrFcJCrqwwILKo720NLR+TFoqSPoLhxBfLqqcUToZboUsFZSRDMmsJa3ZOHmKl+yhSFU3qg6ArTm840BhiG+DG8NZ7toxs/DL/SkUgnl4iOa3NGdINQJZTBMYzavwbENbDg7NL+ICLCFOZ86enB9fdjPPxkP9ch5bAN3+cENdZNhHSvLUi0g9WushpYSHqZBQYiKJbWCb6vSi9XUCDZihkHPk9cdR9oUmyELp3RQSb2c+T9SZNwUZ8SIKt7a26WRz+RFs4+yrPkiNI0mEwQXFbrauywRiXoVpK1OZ5VXld2Tl+iEapuSMapZhiLBxwao1NtXfnThkXMuT4xm14GF7HcRpL3D9JwrGtgED+6fGv5GoDMiDWgYd47hn8kdUF34MkNDGqZHjrlQx2mX7+dOxru++H7hsxYm00+B0K4fnYuHzYoiCWIZ3zPgXXUI/17A=
      - secure: lGcjFCHU8hxT/00624p0lsTEhEoD2sJU1CPMrwbPOcGMBqeJqSZ1w9swTnll7RdbPkheIlf9GmMNts0528nshC1NdMDEDxrE6Aqpwv3JAQj+WiqEBvSZmDSPyiqokhOMkZcrG2GjmDQVn9zj2PkgGHdit9j/4ieidYekMz4xdT1aY5kQ8CWze2qCY/Yl00jMZdoXzj0gQEDpfCkY5uUB9Szrs3aU+I7igEHOST9ipVer0aziSLQeDpyi7fEPTz2dE8cB78AZuThi5MhAA+8ptZ9bOv6V5rrHHTvwHc1l61Iz6FyGIOZsUHMq7Q0SG6GuH/V90+HySelltQwuZmtZx65vV4I4C94eXvz/LEhWnbRcnm/nClsnjYFxHl5SwresJo8rBrGaID7HJ73b17PLJVGZtq910sNWpXI5dI3L+zLYKasIWbraZBQuuUs0haiSjwUV+9GTWXP0nG8LvQUnv2npX3uBn0pbgIFQ5ovwqnmjwuQXs98Elbt4BXuo9DWWiCPzxs2/VkopMJOKvR1Ha0ww5CH3n0188RYF2yJBAdyrm0cZcypp5XRsxvo8KS2jXZ1vfqwBGWTQ6nhQsJIrrsC8RJ5pimilAdjk4sAVnI5ewejINHt5qQcO3FeON1wEZUR5jM4hz3sFigN2J5o7JSQvTSm8Gjqjdr9XJqSBgyQ=
